// <auto-generated />
using System;
using Employee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeModel", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AllocateLeaveQuota")
                        .HasColumnType("bit");

                    b.Property<string>("AlternativeMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendanceLaxity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buddy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBSBypassTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CarAllocated")
                        .HasColumnType("bit");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationResponsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentalDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DirectReportToFunctionHead")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErpCifNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Expatriate")
                        .HasColumnType("bit");

                    b.Property<string>("ExperienceDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherNid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GratuityPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IncrementResponsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDepartmentalHead")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrainer")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssuanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("KnowledgeOfEnglishReading")
                        .HasColumnType("bit");

                    b.Property<bool?>("KnowledgeOfEnglishSpeaking")
                        .HasColumnType("bit");

                    b.Property<bool?>("KnowledgeOfEnglishWriting")
                        .HasColumnType("bit");

                    b.Property<string>("KpiGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveApprovalAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeavePlanHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeavePlanVerifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MailUser")
                        .HasColumnType("bit");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalAllow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherNid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextIncrement")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NonPublicProfile")
                        .HasColumnType("bit");

                    b.Property<string>("OfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PFMember")
                        .HasColumnType("bit");

                    b.Property<string>("ParentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PercentageOfBasicOnGrossSalary")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PoliceVerificationDone")
                        .HasColumnType("bit");

                    b.Property<string>("PresentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionResponsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruitmentChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RenewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequisitionApprovalAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibilityCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RoundOffLeaveBalance")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SalaryAdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SelfAlso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SeparationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeparationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftingGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftingPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SignatureAuthority")
                        .HasColumnType("bit");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SimCardAllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCircle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TaxSubsidy")
                        .HasColumnType("real");

                    b.Property<string>("TaxZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxZoneLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TaxableCarAllocated")
                        .HasColumnType("bit");

                    b.Property<int?>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
